### PR TITLE
feat(subm): request1bld status page

### PR DESCRIPTION
**Pull request by dckc**
This is deployed on a trial basis to https://submit.agoric.app/community/request1bld

### CODE REVIEW

**Comment by dckc** [comment]
limitation: it only scans the last 100 messages. This has mislead people into thinking that requests were addressed or some such.

**Comment by dckc** [comment]
wish: reify this process as Zoe smart contract(s). on devnet?

External inputs:
  - Discord API for finding `authorizedRequests()`
  - Tendermint RPC, i.e. https GET on `searchBySender()`

Outputs:
 - web page with status (ag-solo plug-in?)
 - something to prompt the (human) signer

Google sheets are also possible inputs / outputs.

Do these fit in as ag-solo plug-ins? @michaelfig ?

_p.s. yes; it seems to mostly work: https://github.com/Agoric/validator-profiles/issues/100 -> https://github.com/dckc/ag-admin#readme_

**Comment by michaelfig** [comment]
> Do these fit in as ag-solo plug-ins? @michaelfig ?

I'm not fully oriented, but yes, plugins can do anything Node.js can do.

**Comment by dckc** [comment]
I should probably revert the trial deployment, but it's pretty harmless.

**Pull request closed without merging**
